name: HiveTerm
options:
  bundleIdPrefix: com.hiveterm
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    from: "1.11.0"

targets:
  HiveTerm:
    type: application
    platform: macOS
    sources:
      - path: HiveTerm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hiveterm.HiveTerm
        INFOPLIST_FILE: HiveTerm/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: false
        CODE_SIGN_ENTITLEMENTS: HiveTerm/HiveTerm.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: SwiftTerm

  HiveTermTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: HiveTermTests
    settings:
      base:
        SWIFT_VERSION: "5"
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: HiveTerm
